[tool.poetry]
name = "bdpython"
version = "0.1.0"
description = ""
authors = ["Eryck Santos <dev.erycksantos@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.37"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
